### ISSUE TITLE
VMInfoService - NoClassDefFoundError

### ISSUE THREAD

**Issue by mrsiano** [oVirt/ovirt-vdsmfake#14]
when running vms plenty of this exceptions thrown, we should fix this
@emarcian @rgolangh

[ERROR] 2017-03-09 14:22:53,413 [jsonrpcserver-pool-33]  org.ovirt.vdsmfake.rpc.json.JsonRpcServer run - Failure in processing request
java.lang.NoClassDefFoundError: Could not initialize class org.ovirt.vdsmfake.service.VMInfoService
	at org.ovirt.vdsmfake.service.VMService.fillVmStatsMap(VMService.java:404)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3566)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.ovirt.vdsmfake.service.VMService.getAllVmStats(VMService.java:524)
	at org.ovirt.vdsmfake.rpc.Api.getAllVmStats(Api.java:135)
	at org.ovirt.vdsmfake.rpc.json.commands.GetAllVmStatsCommand.activateApi(GetAllVmStatsCommand.java:17)
	at org.ovirt.vdsmfake.rpc.json.commands.JsonCommand.run(JsonCommand.java:32)
	at org.ovirt.vdsmfake.rpc.json.DefaultCommandExecutor.process(DefaultCommandExecutor.java:11)
	at org.ovirt.vdsmfake.rpc.json.CommandExecutor.execute(CommandExecutor.java:17)
	at org.ovirt.vdsmfake.rpc.json.JsonRpcServer$MessageHandler.run(JsonRpcServer.java:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sandrobonazzola** [comment]
This project is not maintained anymore, closing.
