### ISSUE TITLE
The master branch of engine can't add fakevdsm host

### ISSUE THREAD

**Issue by MarSik** [oVirt/ovirt-vdsmfake#17]
Anything I try, I get:

```
2017-03-29 09:45:32,624+02 ERROR [org.ovirt.engine.core.vdsbroker.VdsManager] (DefaultQuartzScheduler4) [] Exception: org.ovirt.engine.core.vdsbroker.vdsbroker.VDSErrorException: VDSGenericException: VDSErrorException: Failed to GetCapabilitiesVDS, error = Cannot save object, code = 100
	at org.ovirt.engine.core.vdsbroker.vdsbroker.VdsBrokerCommand.createDefaultConcreteException(VdsBrokerCommand.java:76) [vdsbroker.jar:]
	at org.ovirt.engine.core.vdsbroker.vdsbroker.BrokerCommandBase.createException(BrokerCommandBase.java:222) [vdsbroker.jar:]
	at org.ovirt.engine.core.vdsbroker.vdsbroker.BrokerCommandBase.proceedProxyReturnValue(BrokerCommandBase.java:192) [vdsbroker.jar:]
	at org.ovirt.engine.core.vdsbroker.vdsbroker.GetCapabilitiesVDSCommand.executeVdsBrokerCommand(GetCapabilitiesVDSCommand.java:16) [vdsbroker.jar:]
	at org.ovirt.engine.core.vdsbroker.vdsbroker.VdsBrokerCommand.executeVDSCommand(VdsBrokerCommand.java:111) [vdsbroker.jar:]
	at org.ovirt.engine.core.vdsbroker.VDSCommandBase.executeCommand(VDSCommandBase.java:73) [vdsbroker.jar:]
	at org.ovirt.engine.core.dal.VdcCommandBase.execute(VdcCommandBase.java:33) [dal.jar:]
	at org.ovirt.engine.core.vdsbroker.vdsbroker.DefaultVdsCommandExecutor.execute(DefaultVdsCommandExecutor.java:14) [vdsbroker.jar:]
	at org.ovirt.engine.core.vdsbroker.ResourceManager.runVdsCommand(ResourceManager.java:412) [vdsbroker.jar:]
	at org.ovirt.engine.core.vdsbroker.VdsManager.refreshCapabilities(VdsManager.java:679) [vdsbroker.jar:]
	at org.ovirt.engine.core.vdsbroker.monitoring.HostMonitoring.refreshVdsRunTimeInfo(HostMonitoring.java:122) [vdsbroker.jar:]
	at org.ovirt.engine.core.vdsbroker.monitoring.HostMonitoring.refresh(HostMonitoring.java:86) [vdsbroker.jar:]
	at org.ovirt.engine.core.vdsbroker.VdsManager.onTimer(VdsManager.java:274) [vdsbroker.jar:]
	at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source) [:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_121]
	at org.ovirt.engine.core.utils.timer.JobWrapper.invokeMethod(JobWrapper.java:77) [scheduler.jar:]
	at org.ovirt.engine.core.utils.timer.JobWrapper.execute(JobWrapper.java:51) [scheduler.jar:]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz.jar:]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [rt.jar:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_121]
```

**Comment by gregsheremeta** [comment]
What is the exception you see in ovirt-vdsmfake/target/fakevdsm/log/app.log ?

**Comment by MarSik** [comment]
[ERROR] 2017-03-29 14:52:32,138 [jsonrpcserver-pool-35]
 org.ovirt.vdsmfake.rpc.json.commands.JsonCommand run - Can't run api call
java.lang.RuntimeException: Cannot save object
        at org.ovirt.vdsmfake.PersistUtils.store(PersistUtils.java:50)
        at
org.ovirt.vdsmfake.domain.VdsmManager.storeObject(VdsmManager.java:73)
        at
org.ovirt.vdsmfake.domain.VdsmManager.getHostByName(VdsmManager.java:113)
        at
org.ovirt.vdsmfake.service.AbstractService.getActiveHost(AbstractService.java:83)
        at
org.ovirt.vdsmfake.service.HostService.getVdsCapabilities(HostService.java:50)
        at org.ovirt.vdsmfake.rpc.Api.getVdsCapabilities(Api.java:107)
        at
org.ovirt.vdsmfake.rpc.json.commands.GetCapabilitiesCommand.activateApi(GetCapabilitiesCommand.java:17)
        at
org.ovirt.vdsmfake.rpc.json.commands.JsonCommand.run(JsonCommand.java:32)
        at
org.ovirt.vdsmfake.rpc.json.DefaultCommandExecutor.process(DefaultCommandExecutor.java:11)
        at
org.ovirt.vdsmfake.rpc.json.CommandExecutor.execute(CommandExecutor.java:17)
        at
org.ovirt.vdsmfake.rpc.json.JsonRpcServer$MessageHandler.run(JsonRpcServer.java:158)
        at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException:
/home/msivak/Work/ovirt-vdsmfake/target/fakevdsm/cache/Host_test1.oh.vdsm.simulator
(No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at org.ovirt.vdsmfake.PersistUtils.store(PersistUtils.java:46)
        ... 15 more

So I guess some directory is not created automatically.

2017-03-29 14:52 GMT+02:00 Greg Sheremeta <notifications@github.com>:

**Comment by gregsheremeta** [comment]
Yeah if you create that directory you can work around. It's supposed to create it automatically iirc

**Comment by mrsiano** [comment]
seems like the following two patches will fix it, Roy can we merge them?
https://gerrit.ovirt.org/#/c/73936/
https://gerrit.ovirt.org/#/c/73939/4

**Comment by rgolangh** [comment]
https://gerrit.ovirt.org/#/c/73936/ is merged. I'll Close if it this works for you (without creating the dir)
