### ISSUE TITLE
Cannot migrate VM (it still appears on the original host)

### ISSUE THREAD

**Issue by MarSik** [oVirt/ovirt-vdsmfake#20]
I still get the following even when using the right maven. Hosts look online, but a VM can't "migrate", because the engine thinks it still runs on the original host. I am using the UseHostNameIdentifier.

ERROR [jsonrpcserver-pool-26] (JsonRpcServer.java:164) - Failure in processing request
java.lang.NoClassDefFoundError: Could not initialize class org.ovirt.vdsmfake.service.VMInfoService
at org.ovirt.vdsmfake.service.VMService.fillVmStatsMap(VMService.java:402)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3566)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
at org.ovirt.vdsmfake.service.VMService.getAllVmStats(VMService.java:520)
at org.ovirt.vdsmfake.rpc.Api.getAllVmStats(Api.java:120)
at org.ovirt.vdsmfake.rpc.json.commands.GetAllVmStatsCommand.activateApi(GetAllVmStatsCommand.java:17)
at org.ovirt.vdsmfake.rpc.json.commands.JsonCommand.run(JsonCommand.java:35)
at org.ovirt.vdsmfake.rpc.json.DefaultCommandExecutor.process(DefaultCommandExecutor.java:16)
at org.ovirt.vdsmfake.rpc.json.CommandExecutor.execute(CommandExecutor.java:17)
at org.ovirt.vdsmfake.rpc.json.JsonRpcServer$MessageHandler.run(JsonRpcServer.java:162)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)

**Comment by rgolangh** [comment]
@MarSik Can you run 2 VMs on differnt hosts and see that they really belong to this hosts under the hosts->vms subtab?

**Comment by sandrobonazzola** [comment]
This project is not maintained anymore, closing.
